CI: azure
bzip2: '1'
c_compiler: gcc
c_compiler_version: '9'
cdt_name: cos6
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-comp7
expat: '2'
extend_keys:
- ignore_build_only_deps
- ignore_version
- pin_run_as_build
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libffi: '3.3'
lua: '5'
name_suffix: '3.7'
ncurses: '6.2'
numpy: '1.16'
openssl: 1.1.1
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  bzip2:
    max_pin: x
  libffi:
    max_pin: x.x
  ncurses:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  tk:
    max_pin: x.x
  xz:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.8'
r_base: '3.5'
sqlite: '3'
target_platform: linux-64
tk: '8.6'
xz: '5.2'
zip_keys:
- - cdt_name
  - docker_image
zlib: '1.2'
