# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jul 30 12:52:56 2021
# ------------------------------------------------

package:
  name: pypy3.7
  version: 7.3.5
source:
  - folder: pypy3
    patches:
      - patches/0001-Add-conda-forge-version.patch
      - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0018-Disable-copying-dlls.patch
      - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0021-Adapt-platform-to-patch-0001.patch
      - patches/fficurses.patch
      - patches/pre-7.3.6-0001.patch
      - patches/pre-7.3.6-0002.patch
      - patches/pre-7.3.6-0003.patch
      - patches/pre-7.3.6-0004.patch
      - patches/pre-7.3.6-0005.patch
      - patches/pre-7.3.6-0006.patch
      - patches/pre-7.3.6-0007.patch
      - patches/pre-7.3.6-0008.patch
      - patches/pre-7.3.6-0010.patch
      - patches/tklib_build.patch
    sha256: d920fe409a9ecad9d074aa8568ca5f3ed3581be66f66e5d8988b7ec66e6d99a2
    url: https://downloads.python.org/pypy/pypy3.7-v7.3.5-src.tar.bz2
build:
  number: '7'
  skip_compile_pyc:
    - lib*
  string: hc4e864a_7
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_33
    - ca-certificates 2021.5.30 ha878542_0
    - gcc_impl_linux-64 9.3.0 h70c0ae5_19
    - gcc_linux-64 9.3.0 hf25ea35_33
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.2.1 he1b5a44_1007
    - libgcc-devel_linux-64 9.3.0 h7864c58_19
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 11.1.0 h56837e0_4
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - pycparser 2.20 pyh9f0ad1d_2
    - python 2.7.15 h5a48372_1011_cpython
    - python_abi 2.7 1_cp27mu
    - readline 8.1 h46c0cb4_0
    - sqlite 3.36.0 h9cd32fc_0
    - sysroot_linux-64 2.12 he073ed8_14
    - tk 8.6.10 h21135ba_1
    - zlib 1.2.11 h516909a_1010
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.5.30 ha878542_0
    - expat 2.4.1 h9c3ff4c_0
    - gdbm 1.18 h0a1914f_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_4
    - libgomp 11.1.0 hc902ee8_4
    - libstdcxx-ng 11.1.0 h56837e0_4
    - libxcb 1.13 h7f98852_1003
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - readline 8.1 h46c0cb4_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libx11 1.7.2 h7f98852_0
    - xorg-libxau 1.0.9 h7f98852_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - bzip2 >=1.0.8,<2.0a0
    - bzip2 >=1.0.8,<2.0a0
    - expat >=2.4.1,<3.0a0
    - gdbm >=1.18,<1.19.0a0
    - libffi >=3.3,<3.4.0a0
    - libffi >=3.3,<3.4.0a0
    - libgcc-ng >=9.3.0
    - ncurses >=6.2,<6.3.0a0
    - ncurses >=6.2,<6.3.0a0
    - openssl >=1.1.1k,<1.1.2a
    - openssl >=1.1.1k,<1.1.2a
    - sqlite >=3.36.0,<4.0a0
    - sqlite >=3.36.0,<4.0a0
    - tk >=8.6.10,<8.7.0a0
    - tk >=8.6.10,<8.7.0a0
    - xz >=5.2.5,<5.3.0a0
    - xz >=5.2.5,<5.3.0a0
    - zlib >=1.2.11,<1.3.0a0
    - zlib >=1.2.11,<1.3.0a0
  run_constrained:
    - pypy3.5 ==99999999999
    - pypy3.6 ==99999999999
    - python 3.7.* *_73_pypy
test:
  commands:
    - pypy3 --help
    - pypy3 -c "import platform; print(platform._sys_version())"
    - test -f $PREFIX/lib-python/3/lib2to3/Grammar3.7*.pickle
    - test -f $PREFIX/lib-python/3/lib2to3/PatternGrammar3.7*.pickle
about:
  home: http://pypy.org/
  license: MIT
  license_family: MIT
  license_file: pypy3/LICENSE
  summary: 'PyPy is a Python interpreter and just-in-time compiler. See https://conda-forge.org/blog/posts/2020-03-10-pypy
    for more information about using PyPy in conda

    '
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - mattip
    - ocefpaf
    - ohadravid
    - omerbenamram
