# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Dec  7 14:37:32 2020
# ------------------------------------------------

package:
    name: libffi
    version: '3.3'
source:
    sha256: 3f2f86094f5cf4c36cfe850d2fe029d01f5c2c2296619407c8ba0d8207da9a6b
    url: https://github.com/libffi/libffi/archive/v3.3.tar.gz
build:
    number: '2'
    run_exports:
        - libffi >=3.3,<4.0a0
    string: h58526e2_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - autoconf 2.69 pl5320h36c2ea0_10
        - automake 1.16.2 pl5320ha770c72_3
        - binutils_impl_linux-64 2.35.1 h17ad2fc_0
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - gxx_impl_linux-64 7.5.0 h64c220c_13
        - gxx_linux-64 7.5.0 h547f3ba_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35.1 hed1e6ac_0
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libtool 2.4.6 h58526e2_1007
        - m4 1.4.18 h516909a_1001
        - make 4.3 hd18ef5c_1
        - patch 2.7.6 h516909a_1001
        - perl 5.26.2 h36c2ea0_1008
        - sysroot_linux-64 2.12 h77966d4_13
        - texinfo 6.7 pl526he28a2e2_1
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
    run:
        - libgcc-ng >=7.5.0
        - libstdcxx-ng >=7.5.0
test:
    commands:
        - test -e $PREFIX/lib/libffi${SHLIB_EXT}
        - test -e $PREFIX/lib/libffi.a
        - test -e $PREFIX/include/ffi.h
        - test -e $PREFIX/include/ffitarget.h
    requires: null
about:
    description: 'The libffi library provides a portable, high level programming interface

        to various calling conventions. This allows a programmer to call any

        function specified by a call interface description at run-time.

        '
    dev_url: https://github.com/libffi/libffi
    doc_url: https://sourceware.org/libffi/
    home: https://sourceware.org/libffi/
    license: MIT
    license_file: LICENSE
    summary: A Portable Foreign Function Interface Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - scopatz
        - stefan-balke
