# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun 21 19:47:47 2021
# ------------------------------------------------

package:
  name: sqlite
  version: 3.36.0
source:
  patches: null
  sha256: bd90c3eb96bee996206b83be7065c9ce19aef38c3f4fb53073ada0d0b69bbce3
  url: https://www.sqlite.org/2021/sqlite-autoconf-3360000.tar.gz
build:
  number: '0'
  run_exports:
    - sqlite >=3.36.0,<4.0a0
  string: h9cd32fc_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_19
    - gcc_linux-64 9.3.0 hf25ea35_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_19
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - libtool 2.4.6 h58526e2_1007
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - ncurses 6.2 h58526e2_4
    - readline 8.1 h46c0cb4_0
    - zlib 1.2.11 h516909a_1010
  run:
    - libgcc-ng >=9.3.0
    - ncurses >=6.2,<6.3.0a0
    - ncurses >=6.2,<6.3.0a0
    - readline >=8.1,<9.0a0
    - readline >=8.1,<9.0a0
    - zlib >=1.2.11,<1.3.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - sqlite3 --version
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
