# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: python
  version: 3.7.10
build:
  number: 1
  run_exports:
    noarch:
      - python >=3.7,<3.8.0a0
    weak:
      - pypy3.7 >=7.3.5
      - python_abi 3.7 *_pypy37_pp73
  string: 1_73_pypy
  track_features:
    - pypy
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.5.30 ha878542_0
    - expat 2.4.1 h9c3ff4c_0
    - gdbm 1.18 h0a1914f_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pypy3.7 7.3.5 hc4e864a_2
    - readline 8.1 h46c0cb4_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - pypy3.7 7.3.5.*
    - python_abi 3.7 *_pypy37_pp73
test:
  commands:
    - python --version
    - test $(python -c "import sys;print('.'.join(str(i) for i in sys.version_info[:3]))")
      == "3.7.10"
about:
  home: https://github.com/conda-forge/pypy-meta-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Metapackage to select pypy as python implementation
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - mattip
